package com.alura.bytebank

import com.alura.bytebank.exception.InsufficientFoundsException
import com.alura.bytebank.tests.testAccount

fun main() {
    println("main has started")
    testAccount()
//    functionOne()
    println("main has ended")

}
















